language: elixir
elixir:
 - 1.4.5
 - 1.5.2
 - 1.6.6
 - 1.7.4
 - 1.8.1

otp_release:
 - 18.2.1
 - 19.0
 - 20.0
 - 21.0

matrix:
  exclude:
    - elixir: 1.4.5
      otp_release: 21.0
    - elixir: 1.5.2
      otp_release: 21.0
    - elixir: 1.8.1
      otp_release: 19.0

services:
  - postgresql
